[phases.setup]
nixPkgs = ["python311", "google-chrome", "chromedriver", "glib", "nss", "nspr", "atk", "at-spi2-atk", "libdrm", "mesa", "libxkbcommon", "dbus", "pango"]

[phases.build]
cmds = ["pip install -r requirements.txt"]
